  - name: Install acl
    apt:
      name:
        - acl
        - apache2
        # - zabbix-sql-scripts
        # - zabbix-apache-conf
        - php8.1-pgsql
        - zabbix-frontend-php
      state: present
